### ISSUE TITLE
 Gathering Weather Stuff...

### ISSUE THREAD

**Issue by goprojojo** [cowboysdude/MMM-NOAA#10]
After installing the module and setup API it doesn't show information in MagicMirror. Only displaying ' GATHERING WEATHER STUFF'

**Comment by MagicStarthilfe** [comment]
Hi, I wanted to use your module for my MagicMirror, too. But I have the same problem. Valid API keys are available.

**Comment by cowboysdude** [comment]
Open up your developer console and tell me what error you're getting and I can help.

**Comment by MagicStarthilfe** [comment]
Right, I should have sent some more information. Excuse me. At the end of the week I will upload the missing information.

**Comment by cowboysdude** [comment]
It's okay :)  Just glad to help you out...... PS I just uploaded a newer version 4 minutes ago ;)
