### ISSUE TITLE
Installation failure

### ISSUE THREAD

**Issue by E3V3A** [cowboysdude/MMM-NOAA#18]
The `npm install` fails with the following:

```bash
$ npm install

npm WARN deprecated coffee-script@1.10.0: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
npm WARN tar ENOENT: no such file or directory, open '/home/pi/MagicMirror/modules/MMM-NOAA/node_modules/.staging/once-d798dfed/package.json'
...
<several hundred more>
...
npm WARN stylelint-config-recommended@2.0.1 requires a peer of stylelint@^8.3.0 but none is installed. You must install peer dependencies yourself.

npm ERR! code EAI_AGAIN
npm ERR! errno EAI_AGAIN
npm ERR! request to https://registry.npmjs.org/colorguard/-/colorguard-1.2.1.tgz failed, reason: getaddrinfo EAI_AGAIN registry.npmjs.org:443

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2018-01-17T23_12_58_017Z-debug.log
```

Any ideas?

**Comment by cowboysdude** [comment]
Yes did you go to the MagicMirror/modules/MMM-NOAA dir and run npm install?

**Comment by E3V3A** [comment]
> Yes did you go to the MagicMirror/modules/MMM-NOAA dir and run npm install?

Yes, that's exactly where I was running it. (However, not as root.)

PS.
```bash
$ sysinfo
PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
4.9.59-v7+ #1047 SMP Sun Oct 29 12:19:23 GMT 2017

$ nvers
v9.3.0
5.6.0
```

**Comment by cowboysdude** [comment]
You don't want to ever run NPM INSTALL as root......that would not go well
LOL

**Comment by cowboysdude** [comment]
Go to the MagicMirror/modules/MMM-NOAA and type in:

npm install google-translate-api
npm install request

That should fix it!! :)  coffee-script is giving you this problem.

**Comment by E3V3A** [comment]
`requests` was already globally installed.
Indeed that google thing fixed it. But is it really necessary? After all, its a hefty 7 MB addition that I'm not using...

**Comment by cowboysdude** [comment]
I will look into this but I believe that there were issues when it wasn't included.
