### ISSUE TITLE
Clock is not updated except on reload

### ISSUE THREAD

**Issue by E3V3A** [cowboysdude/MMM-NOAA#20]
This is a beautiful weather module! I just wish it would work better.

1. The clock, when shown, doesn't update, until the weather is updated. ~10-15 min
2. The weather temperature is 5 degrees off from what default module is shown. Yes, I understand that it relies on other private peoples weather devices. Can this be changed?

**Comment by cowboysdude** [comment]
Yes I saw that......... The clock and date will be removed as it's not really a needed feature.  That was the plan all along just haven't gotten to it yet.  As of right now it's disabled for any new installs or if you update it will no longer work.    

As for the temp being off you can have it update more.  I cannot fix how wunderground reports the weather :)   It is set to update every 30 * 60 * 1000 you can change that by putting in your config as an option and changing that to update more often and see if that helps .... 

Thank you!

**Comment by E3V3A** [comment]
@cowboysdude  Thanks for your support. 

Yeah, I guess we can't help (and should instead appreciate) that people buy these weather stations, but unfortunately put them in very crappy locations so that the readings are way off. In addition, I notice from that map that some readings have not been updated for a long time...

Cheers. 

BTW. It was not clear at all from the README how to find the `PWS` from that map, or even what it is!
Now I know its a "Pucking Weather Station" found by first selecting some obscure items in the map settings...
