### ISSUE TITLE
"Gathering Weather Stuff"

### ISSUE THREAD

**Issue by Atrion** [cowboysdude/MMM-NOAA#21]
On a Raspberry Pi 3 MagicMirror Setup, I just cloned and did npm install add it to my config (updated with my api) and upon restart it just says "Gathering Weather Stuff" and doesn't display anymore. I was unsure where to ask about this.

**Comment by cowboysdude** [comment]
Run the mirror in dev mode to see what the error is.   😊

**Comment by Atrion** [comment]
I had never run dev mode before, but I just did and There is no error showing. If it matters I am on a jessie lite install (My mirror works in all other ways).

**Comment by cowboysdude** [comment]
It shouldn't matter but possibly.   I will look at it tomorrow it's very
late here :-)
