### ISSUE TITLE
New UI causes high temperatures

### ISSUE THREAD

**Issue by JavierTSalas** [cowboysdude/MMM-NOAA#25]
I've been using this module for a while and it's one of my favorites but my raspberry pi keeps showing the high temp warning whenever the scrolling animation starts. I'm running a raspberry pi 3 b. Is there anyway to get back to the old ui? I'm open to other solutions too.

**Comment by cowboysdude** [comment]
Why don't we try getting rid of the forecast [scrolling section] for you
and see if that helps!

In your custom.css file put this in:

.MMM-NOAA .forehead {
display: none;
}
.MMM-NOAA .fmar {
display: none;
}


Please make sure you have the current NOAA css file  or this won't work :)

Let me know if it helps!!

I also have NOAA version 1 if that doesn't work for you!

**Comment by JavierTSalas** [comment]
I tried editing my MMM-NOAA.css and put that and it didn't work. I also tried making a custom.css and that didn't work either. What file do I put that in? The path I'm editing in it MagicMirror/modules/MMM-NOAA

**Comment by cowboysdude** [comment]
custom.css file is located in the main directory under css

Need to make go to the NOAA repository and get the new css and put that in
modules/MMM-NOAA :)

THEN in the custom.css file that's where you put what I sent :)

If you can't that working then I can send you NOAA V1

**Comment by JavierTSalas** [comment]
So I ran the commands
git reset --hard origin/master
npm install 

then edited my custom.css; Am I doing this right? See below for my custom.css

```
pi@magicpi:~/MagicMirror/modules/MMM-NOAA $ pwd
/home/pi/MagicMirror/modules/MMM-NOAA
pi@magicpi:~/MagicMirror/modules/MMM-NOAA $ cat custom.css
.MMM-NOAA .forehead {
        display: none;
}
.MMM-NOAA .fmar {
        display: none;
}

```
I still see the scrolling forecast

**Comment by cowboysdude** [comment]
Drop this css into the NOAA dir and try again :)

**Comment by cowboysdude** [comment]
Yes your custom css looks right :)

**Comment by cowboysdude** [comment]
I have to leave for a bit but I'll check back later!! Sorry..... duty calls
:)

**Comment by JavierTSalas** [comment]
Which css file? I don't see it. Can you copy and paste the text I don't think github shows email attachments

**Comment by cowboysdude** [comment]
SO SORRY...... if you still need it email me at johnw8017@gmail.com and I'll get it to you! :)
