### ISSUE TITLE
4 Day Forecast temps incorrect

### ISSUE THREAD

**Issue by dherl0623** [cowboysdude/MMM-NOAA#26]
I really like what you've done to the UI of this module. It is great! Upon updating the temperatures in the 4 Day Forecast section seem to sometimes switch to very low temps. I did the math and they are not Celsius, which I thought was the problem in the first place. (I use the imperial system). I wondered why that would be? Where is the forecast being pulled from? Can I change how often it is updated?
![capture](https://user-images.githubusercontent.com/16942160/40122941-ef707874-58f2-11e8-914a-547cf8f66dd3.JPG)

Also, one more thing. Are there any more configuration options then just listed on your Readme? 

Thanks

**Comment by cowboysdude** [comment]
Thank you :-)

I'm'm thinking wunderground s having trouble with API.   My current temp
has been stuck on 75 for three days now.

It's updated quite frequently all day long.   No other config options at
this point.   Why are you looking for something in specific?

**Comment by dherl0623** [comment]
Oh ok, that's very probable then. I think 75 all the time would be perfect personally! Here in Michigan we have some great winters! :-P

Nope, I was just curious. I went through and removed all the other old options in my config file, and nothing broke, so that's good! Maybe getting rid of the air quality sensor? I live in a pretty rural area, so it's not really a concern, and the nearest sensor is over 25 miles away. The module is very nice though! 

Oh look, temps back up to normal :-P

**Comment by dherl0623** [comment]
Ok so yes, I've thought about it some now. Maybe options to hide each section? Forecast, Atmospheric Conditions, Sunset/Sunrise, etc. Probably not 4 Day Forecast as that is the main thing in a weather module. I guess I personally would hide the Atmospheric Conditions and AQ/UV/Wind sections. I may take a look at the CSS and do so, if I get some time.

There are so many freaking cool modules I'm beginning to get a crowded mirror.

**Comment by dherl0623** [comment]
Sorry one more thing, I just noticed a "snapshot.bmp" in the images directory that I don't believe belongs there? It seems like a security camera snapshot from someone's home.

**Comment by cowboysdude** [comment]
That's awesome!!! :)   If you have any other issues let me know!

**Comment by cowboysdude** [comment]
It's official...... Wunderground is dumping their free api keys.....this is all the problem  I have updated NOAA2 to a new provider and will be uploading the files tonight.
