### ISSUE TITLE
Indoor temperature

### ISSUE THREAD

**Issue by idoodler** [cowboysdude/MMM-NOAA#27]
It would be cool if you implement the `INDOOR_TEMPERATURE` event. Some modules use it to share the temperature of the room with other modules like weather modules.

For example MMM-Loxone is emitting it the temperature if the room the mirror is located in. You may want to check out the documentation: https://github.com/idoodler/MMM-Loxone#developer-notes

**Comment by cowboysdude** [comment]
Thank you that's a cool idea.   Right now I'm in the process of having to
redo Noaa because wunderground will no longer work...  BUT as I work on NOAA3 it's a great idea, if I'm not too far along I may just add it ;)

**Comment by cowboysdude** [comment]
Haven't given up on this yet........just up to elbows this is my VERY busy
time of year for work plus still working on NOAA3 ;)

**Comment by idoodler** [comment]
@cowboysdude In my opinion it is easier to implement the indoor temperature when rewriting the module, because you don't have to squeeze in the field after you completed the UI. Contact me, if you need any help:)

**Comment by cowboysdude** [comment]
Yeah I get that but right now the focus is getting the main module to work
without errors lol  getting there

**Comment by idoodler** [comment]
>Yeah I get that but right now the focus is getting the main module to work ...

@cowboysdude Sure. Finish NOAA3, I‘ll make a PullRequest if the feature is missing:)
