### ISSUE TITLE
Wetter Modul wird nicht angezeigt

### ISSUE THREAD

**Issue by MicSchuetz** [cowboysdude/MMM-NOAA#28]
Ich habe das MMM-NOAA installiert aber der Spiegel zeigt keinerlei Daten.

Bin zudem verwundert, muss hier keine Position in der config angegeben werden?

Die IP ist von weather.bit
Hier meine Konfig Datei

	language: "de",
	timeFormat: 24,
	units: "metric",

	modules: [
		{
			module: "alert",
		},
		{
			module: "updatenotification",
			position: "top_bar"
		},
		{
			module: "clock",
			position: "top_left"
		},
		{
    			module: 'MMM-NOAA', 			
			config: {

				apiKey: "3b80fa78278642f187893b24c3576542",    // https://www.wunderground.com/weather/api  select the middle plan... 
				airKey: "98eMyhoyfiiPny7MD"    // IF you want Air Quality Index
			}
		},

		{
			module: "compliments",
			position: "lower_third"
		},
		
		{
			module: "newsfeed",
			position: "bottom_bar",
			config: {
				feeds: [
					{
						title: "Bild News",
						url: "http://www.bild.de/rss3-20745882,feed=alles.bild.html"
					}
				],
				showSourceTitle: true,
				showPublishDate: true
			}
		},
	]

};

**Comment by cowboysdude** [comment]
Sorry would like to help you but I don't understand your language :)
