### ISSUE TITLE
Can't install due to safe-eval Sandbox Breakout

### ISSUE THREAD

**Issue by skippy-oz** [cowboysdude/MMM-NOAA#29]
Hi 
Trying to install MMM-NOAA I do a git fetch to update the module then and npm install which shows "found 1 critical severity vulnerability" then an npm audit to show the critical severity vulnerability safe-eval Sandbox Breakout. I also try npm audit fix and it can't fix it.  see below the output of the commands.  

pi@MagicMirror:~/MagicMirror/modules/MMM-NOAA $ git fetch https://github.com/cowboysdude/MMM-NOAA
remote: Counting objects: 3, done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 3 (delta 2), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (3/3), done.
From https://github.com/cowboysdude/MMM-NOAA
 * branch            HEAD       -> FETCH_HEAD
pi@MagicMirror:~/MagicMirror/modules/MMM-NOAA $ sudo npm install
removed 21 packages, updated 3 packages and audited 1954 packages in 50.545s
found 1 critical severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details
pi@MagicMirror:~/MagicMirror/modules/MMM-NOAA $ sudo npm audit
                                                                                
                       === npm audit security report ===                        
                                                                                
┌──────────────────────────────────────────────────────────────────────────────┐
│                                Manual Review                                 │
│            Some vulnerabilities require your attention to resolve            │
│                                                                              │
│         Visit https://go.npm.me/audit-guide for additional guidance          │
└──────────────────────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Critical      │ Sandbox Breakout                                             │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ safe-eval                                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ No patch available                                           │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ google-translate-api                                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ google-translate-api > safe-eval                             │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/337                       │
└───────────────┴──────────────────────────────────────────────────────────────┘
found 1 critical severity vulnerability in 1954 scanned packages
  1 vulnerability requires manual review. See the full report for details.
pi@MagicMirror:~/MagicMirror/modules/MMM-NOAA $ sudo npm audit fix
up to date in 38.478s
fixed 0 of 1 vulnerability in 1954 scanned packages
  1 vulnerability required manual review and could not be updated

**Comment by cowboysdude** [comment]
Will have to look at it but shouldn't be giving that error

**Comment by cowboysdude** [comment]
I cannot reproduce this error.

**Comment by skippy-oz** [comment]
Hi, I'm running npm version 6.1.0.  I have reflashed the SD card and reinstalled the lastest version of Raspbian with the same result.
Regards
Paul

**Comment by cowboysdude** [comment]
Well all I can tell you is that google translate is not in NOAA3.....that won't fix your issue here but it's coming out soon ;)

**Comment by SamuiSmartHome** [comment]
I do get the same error of Sandbox Breakout and cannot fix it

**Comment by cowboysdude** [comment]
NOAA3 is out....try that.

**Comment by slavko-chedri** [comment]
https://www.npmjs.com/advisories/766 - this is related topic
