### ISSUE TITLE
Not running

### ISSUE THREAD

**Issue by krisspadea** [cowboysdude/MMM-NOAA#30]
Followed the Instructions, but the module isn't coming up when I run my mirror.  
I removed the original openweathermaps modules and added the MMM-NOAA module with the API keys.
Starting the mirror with an npm start from the MagicMirror Directory.
The mirror comes up,  but the module isn't there.  My calendar module is just bumped up into its spot.
Am I missing a step here?

**Comment by cowboysdude** [comment]
Show me your config minus the api keys.

**Comment by krisspadea** [comment]
var config = {
	address: "localhost", // Address to listen on, can be:
	                      // - "localhost", "127.0.0.1", "::1" to listen on loopback interface
	                      // - another specific IPv4/6 to listen on a specific interface
	                      // - "", "0.0.0.0", "::" to listen on any interface
	                      // Default, when address config is left out, is "localhost"
	port: 8080,
	ipWhitelist: ["127.0.0.1", "::ffff:127.0.0.1", "::1"], // Set [] to allow all IP addresses
	                                                       // or add a specific IPv4 of 192.168.1.5 :
	                                                       // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.1.5"],
	                                                       // or IPv4 range of 192.168.3.0 --> 192.168.3.15 use CIDR format :
	                                                       // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.3.0/28"],

	language: "en",
	timeFormat: 12,
	units: "imperial",

	modules: [
		{
			module: "alert",
		},
		{
			module: "updatenotification",
			position: "top_bar"
		},
		{
			module: "clock",
			position: "top_left"
		},
	{
		    module: 'MMM-NOAA',
		    config: {
		
			apiKey: "MY API KEY",    // https://www.wunderground.com/weather/api  select the middle plan... 
			airKey: "MY API KEY"    // IF you want Air Quality Index
		}
	},

		{
			module: "calendar",
			header: "Upcoming Events",
			position: "top_left",
			config: {
				calendars: [
					{
						symbol: "calendar-check-o ",
						url: "webcal://Private Calendar"
					}
				]
			}
		},
{
			module: "calendar",
			header: "US Holidays",
			position: "top_left",
			config: {
				calendars: [
					{
						symbol: "calendar-check-o ",
						url: "webcal://www.calendarlabs.com/templates/ical/US-Holidays.ics"
					}
				]
			}
		},
		{
			module: "newsfeed",
			position: "bottom_bar",
			config: {
				feeds: [
					{
						title: "New York Times",
						url: "http://rss.nytimes.com/services/xml/rss/nyt/World.xml"
					}
				],
				showSourceTitle: true,
				showPublishDate: true
			}
		},
	]

};

/*************** DO NOT EDIT THE LINE BELOW ***************/
if (typeof module !== "undefined") {module.exports = config;}

**Comment by cowboysdude** [comment]
Would be hard for me to tell via this....... do you use TeamViewer at all?  If so I can log in an look to see what's wrong....

**Comment by krisspadea** [comment]
It is possible that I am confusing the API keys.  for the "apiKey", I used the Weatherbit.io key, and for the "airKey", I used the key from AirVisual.  Could this be the problem?


When I went to the WeatherUnderground API page I received this message:


"To improve our services and enhance our relationship with our users, we will no longer provide free weather API keys as part of our program. If you have been directed to download our Weather Underground free API key by a third party provider, please contact your vendor for resolution."



When you click on "Learn more" it brings you to a page with 8 options, and requires you to enter business information and they have someone "reach out to you".


So I'm not sure if the Weatherbit is supposed to replace the WU or if they are supposed to both be used etc.


What are your thoughts?



-----Original Message-----

**Comment by cowboysdude** [comment]
Ohhhhhhhhhhhh wunderground no longer works..... switch to NOAA3.....you have a choice of 7 weather providers there....... ;)
