### ISSUE TITLE
NOAA takes the wrong location

### ISSUE THREAD

**Issue by biker-hannover** [cowboysdude/MMM-NOAA#31]
HI,

I'm living close to Hannover in Lower Saxony and NOAA  took my location about 100 miles to the north to Hamburg. It looks like it uses the location of my provider:

as | "AS8881 1&1 Versatel Deutschland GmbH"
-- | --
city | "Hamburg"
country | "Germany"
countryCode | "DE"
isp | "Versatel Deutschland"
lat | 53.5711
lon | 9.9534
org | "Versatel Deutschland"
query | "82.207.192.63"
region | "HH"
regionName | "Hamburg"
status | "success"
timezone | "Europe/Berlin"
zip | "20259"

Is there a possibility to change the location manually?

Thanks for your answer!

Michael

**Comment by cowboysdude** [comment]
You could hard code your lat and lon inside if you wanted that would/should
give you a more precise location.....

**Comment by biker-hannover** [comment]
In the config.js?

**Comment by biker-hannover** [comment]
It works. Thanks for your support!
